# Generated by Django 5.1.6 on 2025-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories_and_chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blurb',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
